name: Pylint

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint sphinx sphinx_rtd_theme
        pip install -r requirements.txt
        pip install pytest
    - name: Run pylint
      run: |
        pylint --disable=I --disable=W --disable=C --disable=R `find .  -path ./profiling -prune -false -o -name '*.py'`
    - name: Run Tests
      run: |
        sudo apt-get install python-opengl
        pytest -svv p5
